name: cd/deploy-k8s-to-aws-eks-tf

on:
  workflow_run:
    workflows: [cd/create-infra-aws-tf]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/create-k8s-tf-with-api-gateway

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: ff-tech-challenge-eks-cluster

jobs:
  deploy-production:
    name: CD - Deploy K8s to AWS EKS with Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Kube Config
        run: |
          aws eks update-kubeconfig \
          --name ${{ env.CLUSTER_NAME }} \
          --region ${{ env.AWS_REGION }}

      - name: Set Kubernetes envs
        run: |
          envsubst < config/configmap.yaml > config/configmap-f.yaml
          envsubst < config/secrets.yaml > config/secrets-f.yaml
        env:
          DB_ORDER_DSN: ${{ secrets.DB_ORDER_DSN }}
          DB_ORDER_NAME: ${{ secrets.DB_ORDER_NAME }}
          DB_ORDER_USER: ${{ secrets.DB_ORDER_USER }}
          DB_ORDER_PASSWORD: ${{ secrets.DB_ORDER_PASSWORD }}

      - name: Kube Apply
        run: |
          kubectl apply -f namespace.yaml
          kubectl apply -f config/configmap-f.yaml
          kubectl apply -f config/secrets-f.yaml
          kubectl apply -f order-service/
