apiVersion: apps/v1
kind: Deployment
metadata:
  name: tc4-payment-service
  namespace: tech-challenge-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tc4-payment-service
  template:
    metadata:
      labels:
        app: tc4-payment-service
    spec:
      containers:
        - name: tc4-payment-service
          image: ghcr.io/fiap-soat-g20/tc4-payment-service:latest
          ports:
            - containerPort: 80
          env:
            - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
              value: "true"
            - name: MERCADO_PAGO_URL
              valueFrom:
                configMapKeyRef:
                  name: tc4-payment-service-config
                  key: mercado_pago_url
            - name: MERCADO_PAGO_NOTIFICATION_URL
              valueFrom:
                configMapKeyRef:
                  name: tc4-payment-service-config
                  key: mercado_pago_notification_url
            - name: FAKE_MERCADO_PAGO_URL
              valueFrom:
                configMapKeyRef:
                  name: tc4-payment-service-config
                  key: fake_mercado_pago_url
            - name: FAKE_MERCADO_PAGO_NOTIFICATION_URL
              valueFrom:
                configMapKeyRef:
                  name: tc4-payment-service-config
                  key: fake_mercado_pago_notification_url
          resources:
            requests:
              memory: "128Mi" # 128 mebibytes = 134,217,728 bytes = 128 * 1024 * 1024 bytes
              cpu: "100m" # 100 millicores = 0.1 cores, it means 10% of a core
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe: # verify that the container is ready to accept traffic
            httpGet:
              path: /api/v1/health/readyz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe: # verify that the container is running, and restart it if it's not
            httpGet:
              path: /api/v1/health/livez
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
