apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-challenge-config
  namespace: tech-challenge-ns
data:
  jwt_secret: "my-jwt-secret"
  db_order_name: "${DB_ORDER_NAME}" # "fastfood_10soat_g19_tc4_order"
  aws_sqs_order_queue_name: "${AWS_SQS_ORDER_QUEUE_NAME}" # "order-status-updated"
  aws_region: "${AWS_REGION}" # "us-east-1"
  environment: "tech-challenge"
  fake_mercado_pago_url: "http://mock-server.tech-challenge-ns.svc.cluster.local:80/mercadopago/instore/orders/qr"
  fake_mercado_pago_notification_url: "http://tech-challenge-api.tech-challenge-ns.svc.cluster.local:80/api/v1/payments/callback"
  mercado_pago_url: "http://mock-server.tech-challenge-ns.svc.cluster.local:80/mercadopago/instore/orders/qr"
  mercado_pago_notification_url: "http://tech-challenge-api.tech-challenge-ns.svc.cluster.local:80/api/v1/payments/callback"
