apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-secrets
  namespace: tech-challenge-ns
type: Opaque
data: # do not use these values in production
  db_order_user: "${DB_ORDER_USER}" # base64 encoded value of "postgres"
  db_order_password: "${DB_ORDER_PASSWORD}" # base64 encoded value of "postgres"
  db_order_dsn: "${DB_ORDER_DSN}" # base64 encoded value of "postgres://..."
  aws_access_key_id: "${AWS_ACCESS_KEY_ID}" # base64 encoded value of your AWS access key ID
  aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}" # base64 encoded value of your AWS secret access key
  aws_session_token: "${AWS_SESSION_TOKEN}" # base64 encoded value

# In production, you should use a secret management tool like HashiCorp Vault or AWS Secrets Manager
