apiVersion: v1
kind: ConfigMap
metadata:
  name: tc4-customer-service-config
  namespace: tech-challenge-ns
data:
  MONGO_URI: "mongodb://admin:admin@localhost:27017/fastfood_10soat_g22_tc4?authSource=admin"
  MONGO_DATABASE: "fastfood_10soat_g22_tc4"
  MONGO_TIMEOUT: "10s"
  MONGO_MAX_POOL_SIZE: "100"
  MONGO_MIN_POOL_SIZE: "5"
  ENVIRONMENT: "production"
  JWT_SECRET: "SUPER_SECRET_KEY_DONT_TELL_ANYONE"
  JWT_ISSUER: "https://fast-food-auth-abc12345.execute-api.us-east-1.amazonaws.com/prod"
  JWT_AUDIENCE: "https://fast-food-api-def67890.execute-api.us-east-1.amazonaws.com/prod"
  JWT_EXPIRATION: "24h"
