apiVersion: v1
kind: ConfigMap
metadata:
  name: tc4-order-service-config
  namespace: tech-challenge-ns
data:
  jwt_secret: "my-jwt-secret"
  db_order_name: "${DB_ORDER_NAME}" # "fastfood_10soat_g19_tc4_order"
  aws_sqs_order_status_updated_url: "${AWS_SQS_ORDER_STATUS_UPDATED_URL}" # "order-status-updated"
  aws_region: "${AWS_REGION}" # "us-east-1"
  environment: "tech-challenge"
