apiVersion: v1
kind: ConfigMap
metadata:
  name: tc4-payment-service-config
  namespace: tech-challenge-ns
data:
  app-name: "tc4-payment-service" # "fastfood_10soat_g22_tc3"
  app-version: "1.0.0"
  ENVIRONMENT: "development"
  FLASK_APP: "app"
  mercado_pago_url: "http://192.168.0.16:3001/mercadopago/instore/orders/qr"
  fake_mercado_pago_url: "http://mock-server.tech-challenge-ns.svc.cluster.local:80/mercadopago/instore/orders/qr"
  fake_mercado_pago_notification_url: "http://tech-challenge-api.tech-challenge-ns.svc.cluster.local:80/api/v1/payments/callback"
  mercado_pago_url: "http://mock-server.tech-challenge-ns.svc.cluster.local:80/mercadopago/instore/orders/qr"
  mercado_pago_notification_url: "http://tech-challenge-api.tech-challenge-ns.svc.cluster.local:80/api/v1/payments/callback"
  SECRET_KEY: "abcdeABCDE123456"
