apiVersion: v1
kind: ConfigMap
metadata:
  name: tc4-payment-service-config
  namespace: tech-challenge-ns
data:
  app-name: "tc4-payment-service" # "fastfood_10soat_g22_tc3"
  app-version: "1.0.0"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_REGION: "${AWS_REGION}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  DYNAMODB_ENDPOINT: "${DYNAMODB_ENDPOINT}"
  ENVIRONMENT: "development"
  FLASK_APP: "app"
  MERCADO_PAGO_URL: "http://192.168.0.16:3001/mercadopago/instore/orders/qr"
  SECRET_KEY: "abcdeABCDE123456"