apiVersion: v1
kind: ConfigMap
metadata:
  name: tc4-payment-service-config
  namespace: tech-challenge-ns
data:
  app-name: "tc4-payment-service"
  app-version: "1.0.0"
  ENVIRONMENT: "production"
  FLASK_APP: "app"
  FAKE_MERCADO_PAGO_URL: "http://mock-server.tech-challenge-ns.svc.cluster.local:80/mercadopago/instore/orders/qr"
  MERCADO_PAGO_URL: "http://mock-server.tech-challenge-ns.svc.cluster.local:80/mercadopago/instore/orders/qr"
  MERCADO_PAGO_NOTIFICATION_URL: "http://tc4-payment-service.tech-challenge-ns.svc.cluster.local:80/api/v1/payments/callback"
  SECRET_KEY: "abcdeABCDE123456"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
