apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-secrets
  namespace: tech-challenge-ns
type: Opaque
data: # do not use these values in production
  db_order_user: "cG9zdGdyZXM=" # "${DB_ORDER_USER}" # base64 encoded value of "postgres"
  db_order_password: "cG9zdGdyZXM=" # "${DB_ORDER_PASSWORD}" # base64 encoded value of "postgres"
  db_order_dsn: "cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0BmYXN0Zm9vZC0xMHNvYXQtZzE5LXRjNC1vcmRlci5jZ2Ftb2ZnbWVrZGQudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tL2Zhc3Rmb29kXzEwc29hdF9nMTlfdGM0X29yZGVy" # "${DB_ORDER_DSN}" # base64 encoded value of "postgres://..."
  
# In production, you should use a secret management tool like HashiCorp Vault or AWS Secrets Manager
