apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-secrets
  namespace: tech-challenge-ns
type: Opaque
data: # do not use these values in production
  DB_USER: "${DB_ORDER_USER}" # base64 encoded value of "postgres"
  DB_PASSWORD: "${DB_ORDER_PASSWORD}" # base64 encoded value of "postgres"
  DB_DSN: "${DB_ORDER_DSN}" # base64 encoded value of "postgres://..."

# In production, you should use a secret management tool like HashiCorp Vault or AWS Secrets Manager
