apiVersion: apps/v1
kind: Deployment
metadata:
  name: tc4-order-consumer-worker
  namespace: tech-challenge-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tc4-order-consumer-worker
  template:
    metadata:
      labels:
        app: tc4-order-consumer-worker
    spec:
      containers:
        - name: tc4-order-consumer-worker
          image: ghcr.io/fiap-soat-g20/tc4-order-service-worker-consumer:latest
          # ports:
          #   - containerPort: 8081
          envFrom:
            - configMapRef:
                name: tc4-order-service-config
            - secretRef:
                name: tech-challenge-secrets
          resources:
            requests:
              memory: "128Mi" # 128 mebibytes = 134,217,728 bytes = 128 * 1024 * 1024 bytes
              cpu: "100m" # 100 millicores = 0.1 cores, it means 10% of a core
            limits:
              memory: "256Mi"
              cpu: "200m"
