apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-order-worker
  namespace: tech-challenge-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-order-worker
  template:
    metadata:
      labels:
        app: tech-challenge-order-worker
    spec:
      containers:
        - name: tech-challenge-order-worker
          image: ghcr.io/fiap-soat-g20/tc4-order-service-worker-consumer:latest
          # ports:
          #   - containerPort: 8081
          env:
            - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
              value: "true"
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secrets
                  key: db_order_dsn
            - name: AWS_SQS_ORDER_STATUS_UPDATED_URL
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-config
                  key: aws_sqs_order_status_updated_url
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-config
                  key: jwt_secret
          resources:
            requests:
              memory: "128Mi" # 128 mebibytes = 134,217,728 bytes = 128 * 1024 * 1024 bytes
              cpu: "100m" # 100 millicores = 0.1 cores, it means 10% of a core
            limits:
              memory: "256Mi"
              cpu: "200m"
