apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tc4-order-consumer-worker
  namespace: tech-challenge-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tc4-order-consumer-worker
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
