apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-api-mock-server
  namespace: tech-challenge-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-api-mock-server
  template:
    metadata:
      labels:
        app: tech-challenge-api-mock-server
    spec:
      containers:
        - name: tech-challenge-api-mock-server
          image: ghcr.io/fiap-soat-g20/fiap-tech-challenge-3-api-mock-server:latest
          args: ["--data", "/data/definition.json", "--port", "3001"]
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /mercadopago/healthCheck
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /mercadopago/healthCheck
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20
