apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tc4-mock-server
  namespace: tech-challenge-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tc4-mock-server
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
