apiVersion: v1
kind: Service
metadata:
  name: mock-server
  namespace: tech-challenge-ns
spec:
  selector:
    app: tech-challenge-api-mock-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
